document.write('<div id="header-all">');
	document.write('<div id="nav-wrapper">'); 
		document.write('<nav id="nav">');
			document.write('<ul>');
				document.write('<li><a href="index.html">Home</a></li>');
	            document.write('<li><a href="why-us.html">Why Choose Us</a></li>');
	            document.write('<li><a href="transaction.html">Transaction</a></li>');
	            document.write('<li><a href="contact-us.html">Contact Us</a></li>');
            document.write('</ul>');
        document.write('</nav>');
    document.write('</div>');
document.write('</div>');